site_name: Dester Docs
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo/logo-dark-full.svg
  features:
    - navigation.instant
    - announce.dismiss
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github-alt

repo_name: DesterLib - Organization
repo_url: https://github.com/DesterLib

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

# nav:
#   - Home: index.md
#   - Getting started:

nav:
  - What's Dester:
    - index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Prerequisites: getting-started/prerequisite-setup.md
    - Local Deployment: getting-started/local-deployment.md
    - Heroku Deployment: getting-started/heroku-deployment.md
    - Desktop Application: getting-started/desktop-application.md
  - Building:
    - Frontend: building/frontend.md
    - Backend: building/backend.md
    - Desktop: building/desktop.md
  - About:
    - Privacy Policy: additional-info/privacy-policy.md
    - T&C: additional-info/terms-and-conditions.md
    - additional-info/main.md

plugins:
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
      fallback_to_build_date: true