name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-literate-nav mkdocs-minify-plugin mkdocs-git-authors-plugin
      - run: mkdocs gh-deploy --force
